class ValueStr:
    ACQ_TRIGGER_TYPE = "app.Acquisition.Trigger.Type"
    ACQ_TRIGGER_PATTERN = "app.Acquisition.Trigger.Pattern.TriggerPattern"
    ACQ_TRIGGER_MODE = "app.Acquisition.TriggerMode"
    ACQ_TRIGGER_DIGITAL_BIT = "app.Acquisition.Trigger.Pattern.DigitalPatternArrayLogic"
    ACQ_TRIGGER_EDGE_LEVEL = "app.Acquisition.Trigger.Edge.Level"
    ACQ_TRIGGER_EDGE_SOURCE = "app.Acquisition.Trigger.Edge.Source"
    ACQ_FILTER_GLITCHES = "app.Acquisition.Trigger.Pattern.FilterOutGlitches"
    ACQ_HOR_SCALE = "app.Acquisition.Horizontal.HorScale"
    ACQ_HOR_OFFSET = "app.Acquisition.Horizontal.HorOffset"
    ACQ_HOR_SAMPLE_PTS = "app.Acquisition.Horizontal.Maximize"
    ACQ_HOR_SAMPLE_MAX_SMPL = "app.Acquisition.Horizontal.MaxSamples"
    ACQ_HOR_SAMPLE_RATE = "app.Acquisition.Horizontal.SampleRate"

    SAVE_SETUP_FILENAME = "app.SaveRecall.Setup.SaveSetupFilename"
    SAVE_WAVEFORM_SRC = "app.SaveRecall.Waveform.SaveSource"
    SAVE_WAVEFORM_SAVETO = "app.SaveRecall.Waveform.SaveTo"
    SAVE_WAVEFORM_SUBFORMAT = "app.SaveRecall.Waveform.SubFormat"
    SAVE_WAVEFORM_WVFORMAT = "app.SaveRecall.Waveform.WaveFormat"
    SAVE_WAVEFORM_TITLE = "app.SaveRecall.Waveform.TraceTitle"
    SAVE_WAVEFORM_EN_COUNTER_SUFFIX = "app.SaveRecall.Waveform.EnableCounterSuffix"
    SAVE_WAVEFORM_EN_SRC_SUFFIX = "app.SaveRecall.Waveform.EnableSourcePrefix"
    SAVE_WAVEFORM_DIR = "app.SaveRecall.Waveform.WaveformDir"
    SAVE_WAVEFORM_AUTOSAVE = "app.SaveRecall.Waveform.AutoSave"
    SAVE_WAVEFORM_LAST_FILEPATH = "app.SaveRecall.Waveform.LastSavedFilepath"
    SAVE_WAVEFORM_ENABLE_AUTOSAVE = "app.SaveRecall.EnableWaveformOnAutoSave"

    LA_SIGNAL_INPUT_NAME = "app.Logicanalyzer.Digital1.CustomBitname"
    LA_SIGNAL_INPUT_ENABLE = "app.Logicanalyzer.Digital1.Digital"
    LA_DISPLAY_MODE = "app.LogicAnalyzer.Digital1.DisplayMode"
    LA_LABEL_MODE = "app.LogicAnalyzer.Digital1.Labels"
    LA_VIEW = "app.LogicAnalyzer.Digital1.View"
    LA_GRID = "app.LogicAnalyzer.Digital1.UseGrid"
    LA_DESKEW = "app.LogicAnalyzer.Digital1.Deskew"
    LA_THRESHOLD = "app.LogicAnalyzer.MSxxThreshold"

    DISPLAY_GRIDMODE = "app.Display.GridMode"
    PREF_PERFORMANCE = "app.Preferences.Performance"
    HIDE_CLOCK = "app.HideClock"

    DDR_DBG_EnableDDRA = "app.DDRA.EnableDDRA"
    DDR_DBG_Protocol = "app.DDRA.Protocol"
    DDR_DBG_SpeedGrade = "app.DDRA.SpeedGrade"
    DDR_DBG_EnableView = "app.DDRA.EnableView"
    DDR_DBG_EnableDQ = "app.DDRA.EnableDQ"
    DDR_DBG_DataSource = "app.DDRA.DataSource"
    DDR_DBG_EnableDQS = "app.DDRA.EnableDQS"
    DDR_DBG_StrobeSource = "app.DDRA.StrobeSource"
    DDR_DBG_EnableCK = "app.DDRA.EnableCK"
    DDR_DBG_TableRows = "app.DDRA.TableRows"
    DDR_DBG_Analysis = "app.DDRA.Analysis"
    DDR_DBG_MSOSourceWE = "app.DDRA.MSOSourceWE"
    DDR_DBG_EnableWE = "app.DDRA.EnableWE"
    DDR_DBG_MSOSourceCS = "app.DDRA.MSOSourceCS"
    DDR_DBG_EnableCS = "app.DDRA.EnableCS"
    DDR_DBG_MSOSourceCAS = "app.DDRA.MSOSourceCAS"
    DDR_DBG_EnableCAS = "app.DDRA.EnableCAS"
    DDR_DBG_MSOSourceCA4 = "app.DDRA.MSOSourceCA4"
    DDR_DBG_EnableCA4 = "app.DDRA.EnableCA4"
    DDR_DBG_MSOSourceACT = "app.DDRA.MSOSourceACT"
    DDR_DBG_EnableACT = "app.DDRA.EnableACT"
    DDR_DBG_MSOSourceRAS = "app.DDRA.MSOSourceRAS"
    DDR_DBG_EnableRAS = "app.DDRA.EnableRAS"
    DDR_DBG_MSOSourceCA5 = "app.DDRA.MSOSourceCA5"
    DDR_DBG_EnableCA5 = "app.DDRA.EnableCA5"
    DDR_DBG_MSOSourceCLK = "app.DDRA.MSOSourceCLK"
    DDR_DBG_EnableCLK = "app.DDRA.EnableCLK"
    DDR_DBG_MSOSourceCA6 = "app.DDRA.MSOSourceCA6"
    DDR_DBG_EnableCA6 = "app.DDRA.EnableCA6"
    DDR_DBG_MSOSourceCA12 = "app.DDRA.MSOSourceCA12"
    DDR_DBG_EnableCA12 = "app.DDRA.EnableCA12"
    DDR_DBG_MSOSourceCKE = "app.DDRA.MSOSourceCKE"
    DDR_DBG_EnableCKE = "app.DDRA.EnableCKE"
    DDR_DBG_EnableRWSepUsingCmdBus = "app.DDRA.EnableRWSepUsingCmdBus"
    DDR_DBG_CmdBusShow = "app.DDRA.CmdBusShow"
    DDR_DBG_ReadLatency = "app.DDRA.ReadLatency"
    DDR_DBG_WriteLatency = "app.DDRA.WriteLatency"
    DDR_DBG_CmdBusShowAs = "app.DDRA.CmdBusShowAs"
    DDR_DBG_CmdBusTrigger = "app.DDRA.CmdBusTrigger"
    DDR_DBG_CmdBusTriggerOn = "app.DDRA.CmdBusTriggerOn"

    DECODER_ViewDecode = "app.SerialDecode.Decode1.ViewDecode"
    DECODER_Src1 = "app.SerialDecode.Decode1.Src1"
    DECODER_Src2 = "app.SerialDecode.Decode1.Src2"
    DECODER_Src3 = "app.SerialDecode.Decode1.Src3"
    DECODER_Protocol = "app.SerialDecode.Decode1.Protocol"
    DECODER_DDRProtocol = "app.SerialDecode.Decode1.Decode.DDRProtocol"
    DECODER_SpeedGrade = "app.SerialDecode.Decode1.Decode.SpeedGrade"
    DECODER_Dnum_ACT = "app.SerialDecode.Decode1.Decode.Dnum_ACT"
    DECODER_Dnum_CA12 = "app.SerialDecode.Decode1.Decode.Dnum_CA12"
    DECODER_Dnum_CA4 = "app.SerialDecode.Decode1.Decode.Dnum_CA4"
    DECODER_Dnum_CA5_9 = "app.SerialDecode.Decode1.Decode.Dnum_CA5_9"
    DECODER_Dnum_CA6_10 = "app.SerialDecode.Decode1.Decode.Dnum_CA6_10"
    DECODER_Dnum_CAS = "app.SerialDecode.Decode1.Decode.Dnum_CAS"
    DECODER_Dnum_CKE = "app.SerialDecode.Decode1.Decode.Dnum_CKE"
    DECODER_Dnum_CS = "app.SerialDecode.Decode1.Decode.Dnum_CS"
    DECODER_Dnum_RAS = "app.SerialDecode.Decode1.Decode.Dnum_RAS"
    DECODER_Dnum_WE = "app.SerialDecode.Decode1.Decode.Dnum_WE"
    DECODER_ReadLatency = "app.SerialDecode.Decode1.Decode.ReadLatency"
    DECODER_WriteLatency = "app.SerialDecode.Decode1.Decode.WriteLatency"

    # parameterizable config parameters: _ is replaced by for_channel
    p_ACQ_CHX_VIEW = "app.Acquisition.C_.View"
    p_ACQ_CHX_INPUT = "app.Acquisition.C_.ActiveInput"
    p_ACQ_CHX_VER_VARIABLE = "app.Acquisition.C_.VerScaleVariable"
    p_ACQ_CHX_VER_SCALE = "app.Acquisition.C_.VerScale"
    p_ACQ_CHX_VER_OFFSET = "app.Acquisition.C_.VerOffset"
    p_ACQ_CHX_ALIAS = "app.Acquisition.C_.Alias"
    p_ACQ_CHX_GRID = "app.Acquisition.C_.UseGrid"
    p_ACQ_CHX_DESKEW = "app.Acquisition.C_.Deskew"
    p_LA_INVERT = "app.LogicAnalyzer.Invert_"

    def for_channel(ch: int, val_str: str):
        if "_" not in val_str:
            printf(f"only parameterizable CVARs (containing '_' as placeholder) are supported by for_channel!")
            exit(-1)
        return val_str.replace('_', str(ch))


class CmdStr:
    DEFAULT_SETUP = "app.settodefaultsetup"
    SAVE_SETUP_RECALL = "app.SaveRecall.Setup.DoRecallSetupFileDoc2"
    SAVE_SETUP = "app.SaveRecall.Setup.DoSaveSetupFileDoc2"
    WAIT_UNTIL_IDLE = "app.waituntilidle"
    SAVE_SHOW_AUTOSAVE = "app.SaveRecall.ShowAutoSave"
    SAVE_WAVEFORM = "app.SaveRecall.Waveform.SaveFile"
