from .dram_command import DramCommand, E_DRAM_TYPE, DRAM_COMMANDS
from .enums import E_DRAM_CMD, E_DRAM_TYPE
from .ddr4 import DDR4_DRAM_COMMANDS, E_DDR4_DRAM_CMD
from .ddr5 import DDR5_DRAM_COMMANDS, E_DDR5_DRAM_CMD


DRAM_COMMANDS[E_DRAM_TYPE.ddr4] = DDR4_DRAM_COMMANDS
DRAM_COMMANDS[E_DRAM_TYPE.ddr5] = DDR5_DRAM_COMMANDS
